apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: app-b
  app.kubernetes.io/part-of: rendered-manifests-demo

resources:
  - deployment.yaml
  - service.yaml
